Assignment4 docker branch
CS3219-AY2324S1/ay2324s1-course-assessment-g15 pull request #22
Opened 2023-09-28 10:49 UTC by amoonguss1

## Dockerize user service and question service
This PR will introduce docker support for both user and question service, additionally, this completes assignment 4's requirements.
**Checklist:**
- [x] Containerize question repository application.
- [x] Containerize the user profile management application.
**Changes Made:**
- Added Docker Compose configuration for local development.
- Created Dockerfiles for ques and user service.
- Defined environment variables and dependencies in the Docker Compose files.
- Provided instructions for building and running the project in Docker containers.

2023-10-02 04:51 UTC, dsja612 requested changes
LGTM after fixing readme

We might not need elephantSQL anymore, so we should fix the readme accordingly

2023-10-02 04:51 UTC, dsja612 commented on backend/user-service/src/db/dbConfig.ts
> +});
Did some testing:
- This localises the postgres db instance, meaning we can eliminate the need for elephantDB's cloud instance.
- Data also persists in the docker image itself.

GJ 👍

2023-10-02 04:51 UTC, dsja612 commented on dockerfiles/README.md
> +3. Run docker-compose up
Prob need to rewrite this

2023-10-04 08:03 UTC, amoonguss1 commented on dockerfiles/README.md
> +3. Run docker-compose up
Resolved in the following commits

2023-10-04 13:56 UTC, dsja612 approved these changes
lgtm lets merge this after assignment 3

2023-10-06 12:50 UTC, merged